spring.application.name=KGarcia-InventoryApp

spring.thymeleaf.cache=false

spring.servlet.multipart.max-file-size=5MB

spring.datasource.url=jdbc:h2:file:./data/inventory-registration;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=admin
spring.datasource.password=Inventory123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.file.name=logs/inventory-registration.log
debug=true

